### ISSUE TITLE
chat bubble

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/hap#109]
Live chat bubble still gets in way for users on mobile phone.  Need to refresh page to have intercom notice what page we are on and make the bubble disappear.  

Might be an issue with the way pages are loading on our end, maybe there is a way to have the pages refresh when moving from landing to apply page so that intercom can notice we are on apply page without refreshing and automatically remove the chat bubble so it doesn't get in the way.

**Comment by ChristopherHarwell** [comment]
Are we still using Zendesk?

**Comment by iesous-kurios** [comment]
Not at the moment, but might go back to it in the future.
