### ISSUE TITLE
delete users

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/hap#11]
As an admin, I can delete user accounts

**Comment by joeywire** [comment]
Running into an issue when deleting users. If we delete them completely we will no longer be able to see their names on any archived requests (pulling it via a foreign key to `users`). 

Planning on archiving the users as well (or maybe toggling them to in-active). It will add some refactoring work but it would help keep a more accurate record of requests.

**Comment by iesous-kurios** [comment]
Yeah, that's a good catch and good idea

It certainly isn't going to be an issue of cost or space to just keep the users in our database but 'inactive' or 'archived'

Will likely still want admins to have full CRUD though of both users and requests.

**Comment by iesous-kurios** [comment]
Closing this since we have a crud users issue open
