### ISSUE TITLE
Client contact information

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/hap#114]
@J When you pushed the changes to add the Landlord name, we lost access to the clients phone number

**Comment by ChristopherHarwell** [comment]
Has this been fixed yet? If not I will start working on this tomorrow morning.

**Comment by iesous-kurios** [comment]
Don't think it has been yet

**Comment by ChristopherHarwell** [comment]
When you say client are you referring to the Tenant?

**Comment by iesous-kurios** [comment]
Yes, I accidentally removed the tenant phone number when I made the
"contact" tab a "landlord contact " tab at the request of prevention team
