### ISSUE TITLE
Merge Duplicates?

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/hap#116]
Possibly make ability to merge requests instead of deleting duplicates?

Not sure.  

Might just stick with deleting duplicates.

**Comment by isaiah-j** [comment]
Yeah, it makes more sense to delete them. Both requests will have the same information so there isn't any pros for merging that I can think of

**Comment by iesous-kurios** [comment]
Yeah, sounds good to me, closing issue
