### ISSUE TITLE
Approval confirmation 

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/hap#119]
Double check that a notification is being created and displayed for users, including instant notification that the request a program manager is attempting to approve was or wasn't approved when they clicked. 

Granted,  I tested on phone,  not a pc

Will check on laptop and report back

**Comment by iesous-kurios** [comment]
Also with this, the approval isn't sending email to tenant unless the approval status request button is changed. 

I might be able to troubleshoot this one. 

I might have deleted the function to send email to tenant upon approval.

**Comment by ChristopherHarwell** [comment]
@isaiah-j are you working on this if not, then i will work on it. I believe i found the cause of the bug for [Issue #114 ](https://github.com/fp-rap-build/hap/issues/114), so once i confirm that I have indeed found the cause of the bug, I will start working on this issue unless you have taken care of it already.

**Comment by ChristopherHarwell** [comment]
Can confirm that this does NOT work when approving a request but works when denying a request

**Comment by ChristopherHarwell** [comment]
Working on a fix now
