### ISSUE TITLE
Back to orgs

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/hap#28]
Need navigation button to get back to org management from program/budget screen

Currently need to go back to landing with HAP link on top left or log out to get out of program/budget management 

![Screenshot_20210502-001959_Chrome.jpg](https://user-images.githubusercontent.com/11794794/116805590-5de8d880-aadc-11eb-8b04-d0020dc5f355.jpg)

**Comment by isaiah-j** [comment]
Added button in the top right that redirects back to the admin dashboard. Trying to navigate back to the organizations table is tricky, since all of the admin pages are controlled by state instead of having their own URLs. Will come back to this after finishing the high priority issues

**Comment by iesous-kurios** [comment]
Cool, that is definitely a good temp solution that is definitely not as
important as the
other stuff you are working on.  Timeline sounds good to me.

J. Wylie

**Comment by ChristopherHarwell** [comment]
Is this still an open issue @iesous-kurios if so I have some free time this week and will tackle this.

**Comment by iesous-kurios** [comment]
Looks like a fix Isaiah pushed for going back to most recent dashboard fixed this as well
