### ISSUE TITLE
Mobile view

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/hap#66]
Next button is hard to get to with floating objects in the way. 

Not sure of best solution. 

Will see about other placement options for floating link to chat and family promise 

![Screenshot_20210513-123812_Chrome.jpg](https://user-images.githubusercontent.com/11794794/118177987-4668f400-b3e8-11eb-9a15-2af77557f433.jpg)

**Comment by iesous-kurios** [comment]
Might be resolved.  I had the button disappear on apply and admin pages

**Comment by ChristopherHarwell** [comment]
Is this still an open issue? I'm not seeing a chat bubble or a link on mobile in my local environment
![Uploading Screenshot 2021-06-08 at 10-50-04 Family Promise RAP.png…]()

**Comment by iesous-kurios** [comment]
Still an issue, I removed the chat button because it gets in the way of the
"next" button on mobile, and apparently most our users are on mobile.

I can make the im chat bubble appear on certain pages,  but the text chat
bubble is all or nothing
