### ISSUE TITLE
Monthly Rent

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/hap#7]
As a program manager, I can view how much a tenant pays for rent monthly

**Comment by isaiah-j** [comment]
Finished, although for old requests the monthly rent will show up as null. Decided to keep it that way since defaulting it to "0" would be misleading. Hopefully that doesn't cause any confusion

**Comment by iesous-kurios** [comment]
No, that's perfect, thanks

In the future, this should be added to the CRUD that program managers are allowed to do.  If needed, once that is implemented, we can go in and manually update the monthly rent for the null values.
