### ISSUE TITLE
Children ages

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/hap#9]
Made this a separate issue from the total children, since this will likely be more involved.  

As a program manager, I can see the ages of the children in the household 

(for right now, the messaging can be used to ask the tenant what the ages of their children are, but we will need to report on the ages of the children we have served so having a spot to put that data and query it will be needed)

**Comment by iesous-kurios** [comment]
This issue will likely resolve this issue as well:

https://github.com/fp-rap-build/hap/issues/113

**Comment by iesous-kurios** [comment]
This might be fixed with the new user dashboard?

**Comment by joeywire** [comment]
feature added with PR #161
