### ISSUE TITLE
Comments notifications

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/hap#98]
Program managers have requested that comments to requests also trigger the notifications panel

If that was previously working, it isn't anymore:

<img width="1680" alt="Screen Shot 2021-05-26 at 1 56 43 PM" src="https://user-images.githubusercontent.com/11794794/119730215-5510cb80-be2a-11eb-8a78-0712eea724a2.png">

**Comment by isaiah-j** [comment]
Tested this out and it's working, make sure you're subscribed to the request you want to receive notifications for
